---
sudo: required
language: ruby
cache: bundler

bundler_args: --without integration tools

before_install:
  - gem install bundler
  - gem --version

branches:
  only:
  - master

matrix:
  include:
  - rvm: 2.3.8
    script: bundle exec rake
  - rvm: 2.4.5
    script: bundle exec rake
  - rvm: 2.5.3
    script: bundle exec rake